plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.5'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.4.1'
}

group = 'org.example'
version = '0.0.0'

ext {
    gdxVersion = '1.13.1'
}

repositories {
    mavenCentral()

    maven { url "https://sonatype.org" }
}

sourceSets {
    src {
        java.srcDirs = ['main']
        resources.srcDirs = ['assets']
    }
}

dependencies {
    implementation 'uk.co.electronstudio.jaylib:jaylib:6.0.1-0'
    implementation 'com.google.code.gson:gson:2.14.0'

    compileOnly 'org.jetbrains:annotations:24.1.0'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

idea {
    project {
        settings {
            runConfigurations {
                "Main"(org.jetbrains.gradle.ext.Application) {
                    mainClass = "org.example.Main"
                    moduleName = "${project.name}.main"
                    workingDirectory = rootProject.projectDir.absolutePath
                    jvmArgs = "-XstartOnFirstThread"
                }

                "Client"(org.jetbrains.gradle.ext.Application) {
                    mainClass = "org.example.client.Main"
                    moduleName = "${project.name}.main"
                    workingDirectory = rootProject.projectDir.absolutePath
                    jvmArgs = "-XstartOnFirstThread"
                }
            }
        }
    }
}

application {
    mainClass = "org.example.Main"

    applicationDefaultJvmArgs = ["-XstartOnFirstThread"]
}

jar {
    manifest {
        attributes(
                'Main-Class': "org.example.Main"
        )
    }
}

run {
    workingDir = rootProject.projectDir
}

test {
    useJUnitPlatform()
}

import org.gradle.internal.os.OperatingSystem

if (OperatingSystem.current().isMacOsX()) {
    tasks.withType(JavaExec).configureEach {
        jvmArgs += "-XstartOnFirstThread"
    }
}